# Generated by Django 4.2.5 on 2024-03-23 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_trainingdataset_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingdataset',
            name='remarks',
        ),
    ]
