# Generated by Django 4.2.5 on 2024-03-23 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_trainingdataset_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingdataset',
            name='medicine_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.medicines'),
        ),
    ]
