# Generated by Django 4.2.5 on 2024-03-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_testingdataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=None, null=True),
        ),
    ]
